# Generated by Django 3.2.4 on 2021-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210702_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'doing'), ('done', 'done')], max_length=7),
        ),
    ]
